// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPis5vTGYFVWSVkRgkb0d30VZYeVF0O8',
    appId: '1:179234530731:web:3ffd9274f92c1fd7991eee',
    messagingSenderId: '179234530731',
    projectId: 'tour-matee',
    authDomain: 'tour-matee.firebaseapp.com',
    storageBucket: 'tour-matee.firebasestorage.app',
    measurementId: 'G-LBEGJWFP0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0Ht1PyTKTeExjbx1nj_kog2vFLn-sdjo',
    appId: '1:179234530731:android:0e1482f31aa83af0991eee',
    messagingSenderId: '179234530731',
    projectId: 'tour-matee',
    storageBucket: 'tour-matee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1GMe9vMfqkNBV4Uhq4DvfMXsfrhWwEek',
    appId: '1:179234530731:ios:139db556836dab55991eee',
    messagingSenderId: '179234530731',
    projectId: 'tour-matee',
    storageBucket: 'tour-matee.firebasestorage.app',
    iosBundleId: 'com.example.tourMatee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1GMe9vMfqkNBV4Uhq4DvfMXsfrhWwEek',
    appId: '1:179234530731:ios:139db556836dab55991eee',
    messagingSenderId: '179234530731',
    projectId: 'tour-matee',
    storageBucket: 'tour-matee.firebasestorage.app',
    iosBundleId: 'com.example.tourMatee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiPis5vTGYFVWSVkRgkb0d30VZYeVF0O8',
    appId: '1:179234530731:web:1364d49ea4b7f26c991eee',
    messagingSenderId: '179234530731',
    projectId: 'tour-matee',
    authDomain: 'tour-matee.firebaseapp.com',
    storageBucket: 'tour-matee.firebasestorage.app',
    measurementId: 'G-DLYGJP9PBP',
  );
}
